# general settings
name: GoPro-HINet
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10 

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/train/sharp_crops.lmdb
    dataroot_lq: ./datasets/GoPro/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1 # 数据集的原始规模未被放大
    prefetch_mode: cpu

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/test/target.lmdb
    dataroot_lq: ./datasets/GoPro/test/input.lmdb
    io_backend:
      type: lmdb

# network structures
network_g:
  type: HINet
  wf: 64
  hin_position_left: 3
  hin_position_right: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
#  visualization: visual/ntire2021-demo

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 4000
    eta_min: !!float 1e-7

  total_iter: 4000  # 将 total_iter 改为 N，需同时设置 scheduler.T_max = N，确保学习率正确衰减 原400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 0.5
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2 # 原 5e4 每 5 万次迭代验证一次，共验证 400000 / 50000 = 8 次
  save_img: false
  grids: true
  crop_size: 256
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20   # 每 20 次迭代输出一次日志
  save_checkpoint_freq: !!float 2e2 # 原2e4 每 2 万次保存一次模型
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
